# Generated by Django 5.0.14 on 2025-04-25 08:27

import django.db.models.deletion
import verification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('ID_CARD', 'Лична карта'), ('PASSPORT', 'Паспорт')], max_length=50, null=True)),
                ('front_image', models.ImageField(upload_to=verification.models.user_directory_path)),
                ('back_image', models.ImageField(blank=True, null=True, upload_to=verification.models.user_directory_path)),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to=verification.models.user_directory_path)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Изчаква качване'), ('PROCESSING', 'Обработва се'), ('NEEDS_SELFIE', 'Нужно е селфи/видео'), ('VERIFIED', 'Верифициран'), ('FAILED_DATA', 'Неуспешно извличане на данни'), ('FAILED_MATCH', 'Несъответствие на лице'), ('FAILED_MANUAL', 'Отхвърлен ръчно')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
