# Generated by Django 5.2 on 2025-04-24 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('лицева_верификация_успешна', models.BooleanField(default=False)),
                ('документ_верификация_успешна', models.BooleanField(default=False)),
                ('жив_човек_верификация_успешна', models.BooleanField(default=False)),
                ('сканирани_данни_предна_страна', models.JSONField(blank=True, null=True)),
                ('сканирани_данни_задна_страна', models.JSONField(blank=True, null=True)),
                ('време_на_верификация', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
