# Generated by Django 5.0.14 on 2025-04-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='date_of_expiry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='date_of_issue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='document_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ocrimage',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
